### ISSUE TITLE
Destroy resource still in pool

### ISSUE THREAD

**Issue by Jeroenimoo0** [coopernurse/node-pool#168] opened 2016-12-08 10:26 UTC
If you call destroy() on a on a resource which is still in the pool you will get an error 'Resource not currently part of this pool'.

I listen to errors on my connection and want to destroy the connection if a fatal error has been thrown. I can't do this currently because the resource may not be acquired when this error is thrown.

**Comment by sandfox** [comment] 2016-12-08 16:03
duplicate of https://github.com/coopernurse/node-pool/issues/155
Currently there is no built in way to do this and it can only be implemented through userland code, but I'm looking at how to add it generically to the pool.

**Closed by sandfox** 2016-12-08 16:03 UTC
